baseURL = "http://www.evocations.info"
languageCode = "en-us"
title = "Evocations"
theme = "customdiary" 
copyright = "evocations.info 2020"


[[menu.main]]
url = "/contact"
name = "Contact"
weight = 98

[[menu.main]]
url = "/about"
name = "About"
weight = 99

[[menu.main]]
url = "/downloads"
name = "Downloads"
weight = 2

[[menu.main]]
url = "/blog"
name = "Blog"
weight = 3

