languageCode = "en-us"
contentdir = "content"
publishdir = "public"
builddrafts = false
baseUrl = "http://evocations.info"
canonifyurls = true
title = "Evocations"
author = "t0fu"
theme = "pixyll"
disqusShortname = "evocations.info"
create_search_index = true

[indexes]
  category = "categories"
  tag = "tags"
  blog = "content/blog"

[params]
  search_engine = true
  google_analytics_id = "XX-XXXXXXXX-X"
  twitter_username = "iamt0fu"
  paginate = true
